setwd("C:\Users\timon\Documents\R\SDA\ass2")
source("sample2020.txt")

x=seq(0,1,by=.01)
normal<- qnorm(x,mean=1,sd=sqrt(4))
qt3 <-qt(x,3) 
plot(normal)
plot(qt3)
plot(normal,qt3)
plot(qt3,normal)

snormal <- qnorm(x,mean=0,sd=1)
uni<-qunif(x,min=1,max=2)
plot(uni)
plot(snormal)
plot(uni,snormal)

t10<-qt(x,10)
log<-qlnorm(x,meanlog = 0.1,sdlog = 0.4)
plot(t10)
plot(log)
plot(t10,log)
